name: DrestoriamBuilds
version: '1.0'
main: org.Drestoriam.drestoriamBuilds.DrestoriamBuilds
api-version: 1.21
authors: [ billbominecraft ]
depend: [ WorldEdit, Citizens, helper ]
commands:
  bp:
    description: General usage command for DrestoriamBuilds
    usage: /bp <help/create/update/[blueprint]/npchere/npcremove>
